version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    build:
      context: .
    ports:
      - "8084:8084"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "81:81"
    depends_on:
      - django_gunicorn

volumes:
  static:
