server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/giggyapp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
      properties.hibernate.format_sql : true
    show-sql : true

  redis :
    host : localhost
    port : 6379

  profiles :
    include : keys

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
